spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/demoSpringBoot
  username: postgres
  password: justice
  driver: driver-class-nam:org.postgresql.Driver	
 jpa:
  properties:
   hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    temp:
     use_jdbc_metadata_defaults: false	
    ddl-auto: update
